-- CreateTable
CREATE TABLE "ORIGIN_SCHEMETYPE" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "SchemeType" TEXT NOT NULL,
    "SchemeMode" TEXT NOT NULL,
    "SCHEMECODE" TEXT NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "ORIGIN_SCHEMETYPE_SCHEMECODE_key" ON "ORIGIN_SCHEMETYPE"("SCHEMECODE");
