"use client";

import { Inter } from "next/font/google";
import { Overlock } from "next/font/google";

import "./globals.css";
import LoadingScreen from "@/components/loading/Loading";
import { useState, useEffect } from "react";


const inter = Inter({ subsets: ["latin"] });

const overlock = Overlock({
  subsets: ['latin'],
  weight: ['400', '700', '900']
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => setLoading(false), 2000);
    return () => clearTimeout(timer);
  }, []);

  return (
    <html lang="en">
      <body className={overlock.className}>{loading ? <LoadingScreen /> : children}</body>
    </html>
  );
}
